core/iam/src/basic/dto/iam_account_dto.rs, core/iam/src/basic/dto/iam_cert_conf_dto.rs, core/iam/src/basic/dto/iam_tenant_dto.rs, core/iam/src/basic/serv/iam_account_serv.rs, core/iam/src/basic/serv/iam_cert_ldap_serv.rs, core/iam/src/basic/serv/iam_tenant_serv.rs, core/iam/src/console_common/api/iam_cc_account_api.rs, core/iam/src/console_passport/api/iam_cp_cert_api.rs, core/iam/src/console_passport/dto/iam_cp_cert_dto.rs, core/iam/src/console_passport/serv/iam_cp_cert_ldap_serv.rs, core/iam/tests/test_iam_scenes_app.rs, core/iam/tests/test_iam_scenes_common.rs, core/iam/tests/test_iam_scenes_passport.rs, core/iam/tests/test_iam_scenes_system.rs, core/iam/tests/test_iam_scenes_tenant.rs
remove add_mail_vcode_cert and delete_mail_vcode_cert function
=> reopen mail login code

core/iam/src/basic/serv/iam_cert_ldap_serv.rs, core/iam/tests/test_basic.rs, core/iam/tests/test_iam_scenes_common.rs
=> Iam test ldap api

core/iam/src/console_passport/api.rs, core/iam/src/console_passport/api/iam_cp_app_api.rs, core/iam/src/iam_initializer.rs
add /cp/app api，query by account-app rel
=> add_cp_app_api

middleware/event/tests/test_event_with_event_code.rs, middleware/event/tests/test_event_with_im.rs, spi/spi-stats/src/api/ci/stats_ci_record_api.rs, spi/spi-stats/src/serv/pg/stats_pg_record_serv.rs, spi/spi-stats/tests/test_stats_record.rs, support/auth/src/api/auth_mgr_api.rs, support/auth/tests/test_auth_encrypt.rs, support/iam/src/basic/serv/iam_account_serv.rs, support/iam/src/iam_initializer.rs, support/iam/tests/test_cc_set.rs, support/iam/tests/test_key_cache.rs
modified:   middleware/event/tests/test_event_with_im.rs
modified:   spi/spi-stats/src/api/ci/stats_ci_record_api.rs
modified:   spi/spi-stats/src/serv/pg/stats_pg_record_serv.rs
modified:   spi/spi-stats/tests/test_stats_record.rs
modified:   support/auth/src/api/auth_mgr_api.rs
modified:   support/auth/tests/test_auth_encrypt.rs
modified:   support/iam/src/basic/serv/iam_account_serv.rs
modified:   support/iam/src/iam_initializer.rs
modified:   support/iam/tests/test_cc_set.rs
modified:   support/iam/tests/test_key_cache.rs
=> 	modified:   middleware/event/tests/test_event_with_event_code.rs

middleware/flow/src/dto/flow_inst_dto.rs, middleware/flow/tests/test_flow_scenes_fsm.rs, spi/spi-conf/fmt_and_fix.sh, spi/spi-conf/src/api/nacos.rs, spi/spi-conf/src/api/nacos/v1/config_service.rs, spi/spi-conf/src/api/nacos/v1/namespace.rs, spi/spi-conf/src/api/nacos/v2/config_service.rs, spi/spi-conf/src/api/nacos/v2/namespace.rs, spi/spi-conf/tests/spi_conf_nacos_compatible_test.rs
support basic-auth for spi nacos api
=> spi-conf: support basic-auth-loggin

middleware/schedule/src/api/ci/schedule_ci_job_api.rs, middleware/schedule/src/dto/schedule_job_dto.rs, middleware/schedule/src/lib.rs, middleware/schedule/src/serv/schedule_job_serv.rs, middleware/schedule/tests/test_basic_schedual_service.rs, middleware/schedule/tests/test_multi.rs, spi/spi-kv/src/api/ci/kv_ci_item_api.rs
1. remove unwrap used in shedule
2. fix read from kv failed
=> schedule: remove unwrap used in shedule

middleware/schedule/Cargo.toml
Move tokio-cron-scheduler source to personal fork
=> schedule: fix utc issue

spi/spi-conf/src/api/nacos.rs, spi/spi-conf/src/api/nacos/v1/config_service.rs, spi/spi-conf/src/api/nacos/v1/namespace.rs, spi/spi-conf/src/dto/conf_auth_dto.rs, spi/spi-conf/src/dto/conf_config_nacos_dto.rs, spi/spi-conf/tests/spi_conf_nacos_compatible_test.rs
spi-conf: Support carring login information in form
=> spi-conf: support login in form body

spi/spi-conf/src/api/nacos.rs, spi/spi-conf/src/api/nacos/v1/config_service.rs, spi/spi-conf/src/api/nacos/v1/mod.rs, spi/spi-conf/src/dto/conf_config_nacos_dto.rs
1. allow auth by params
2. fix publish config api
=> spi-conf: allow auth by params

spi/spi-conf/Cargo.toml, spi/spi-conf/src/dto/conf_config_dto.rs, spi/spi-conf/src/serv/pg/conf_pg_namespace_serv.rs, spi/spi-conf/tests/config/conf-default.toml, spi/spi-conf/tests/spi_conf_api_test.rs, spi/spi-conf/tests/spi_conf_test_common.rs
1. modifiy namespace that does not exist will return 404 notfound
2. add test case for this
=> spi-conf: fix: modifiy namespace does not exist will return 404

spi/spi-conf/src/api/nacos/v1/auth.rs, spi/spi-conf/src/dto/conf_config_nacos_dto.rs
add auth/users/login api for spi-conf
=> spi-conf: add auth/users/login api

.github/workflows/service-all-push.yml, .github/workflows/service-all-release.yml
Support to build with poem-grpc dependency.
=> global: add setup-protoc in github workflow

gateway/spacegate/Cargo.toml, gateway/spacegate/src/plugin/anti_replay.rs, gateway/spacegate/src/plugin/anti_xss.rs, gateway/spacegate/src/plugin/audit_log.rs, gateway/spacegate/src/plugin/auth.rs, gateway/spacegate/src/plugin/ip_time/mod.rs
Apply spacegate update on bios gateway plugins
1. use `Body` instead of `Vec<u8>` in plugins
2. update method names
=> apply spacegate update on bios gateway plugins

spi/spi-stats/src/api/ci/stats_ci_record_api.rs, spi/spi-stats/src/serv/pg/stats_pg_metric_serv.rs, spi/spi-stats/src/serv/pg/stats_pg_record_serv.rs, spi/spi-stats/src/serv/stats_record_serv.rs, spi/spi-stats/tests/test_stats_record.rs
And some ohter changes are make by code formatter
=> spi-stats: add query many fact record interface

basic/src/spi/spi_initializer.rs
The generated index name shouldn't exceed 63.
If the index name is too long, the overflowed part will be truncated, which would make many indexes share a same name and only the first one will be create.
=> Global: fix index name confict bug

Cargo.toml, basic/Cargo.toml, basic/src/rbum/rbum_enumeration.rs, gateway/spacegate/Cargo.toml, middleware/flow/Cargo.toml, middleware/flow/src/dto/flow_state_dto.rs, middleware/flow/src/dto/flow_transition_dto.rs, middleware/flow/src/dto/flow_var_dto.rs, middleware/flow/src/serv/flow_rel_serv.rs, sdk/invoke/Cargo.toml, sdk/invoke/src/invoke_enumeration.rs, spi/spi-plugin/Cargo.toml, spi/spi-plugin/src/plugin_enumeration.rs, spi/spi-stats/Cargo.toml, spi/spi-stats/src/stats_enumeration.rs, support/iam/Cargo.toml, support/iam/src/iam_enumeration.rs
update tardis version to beta 12
=> split: update tardis version to beta 12

services/spi-conf/src/main.rs, spi/spi-conf/src/api/nacos/grpc/mod.rs, spi/spi-conf/tests/spi_conf_test_common.rs
add more nacos error codes to guide client behavior
=> spi-conf: Spi conf add more nacos error codes

support/reach/src/api/reach_api_ct/reach_api_ct_trigger_instance.rs, support/reach/src/dto/trigger/global_config.rs, support/reach/src/serv/trigger_global_config.rs, support/reach/src/serv/trigger_instance_config.rs, support/reach/src/task/message_send_listener.rs
1. Fix reach config use optional signature
2. Fix query instance config
=> reach: Fix reach config use optional signature, fix query instance config

support/reach/src/reach_consts.rs, support/reach/src/reach_init.rs, support/reach/src/serv/message_send.rs, support/reach/src/serv/trigger_global_config.rs, support/reach/src/task/message_send_listener.rs
[fix cannot add trigger config with empty id](https://github.com/ideal-world/bios/commit/9c4c57c93755a3ebfb616bab88081c67f37b0c1a)
=> reach: fix cannot add trigger config with empty id

spi/spi-conf/src/api/ci/conf_auth.rs, spi/spi-conf/src/dto/conf_auth_dto.rs, spi/spi-conf/tests/spi_conf_api_test.rs
1. Fix conf nacos password validation
2. create app's namespace after bundle register
=> spi-conf: Fix conf nacos password validation, create app's namespace after bundle register

.gitignore, middleware/flow/src/api/cc/flow_cc_inst_api.rs, middleware/flow/src/dto/flow_var_dto.rs, middleware/flow/src/serv/flow_inst_serv.rs
This reverts commit b38d97456652b15c6e260a55ef8fc0fcd532968a.
=> Revert "Revert "feat(flow): add default value (#567)" (#578)"

Cargo.toml, services/bios-all/Cargo.toml
new config should add `k8s_ns`
```toml
[fw.cluster]
k8s_ns="example"
kbs_svc="bios"
```
=> Update tardis version to fix k8s issue

backend/basic/src/rbum/rbum_config.rs, backend/services/bios-all/Cargo.toml, backend/supports/reach/src/domain/message.rs, backend/supports/reach/src/domain/message_signature.rs, backend/supports/reach/src/domain/message_template.rs, backend/supports/reach/src/domain/reach_vcode_strategy.rs, backend/supports/reach/src/domain/trigger_global_config.rs, backend/supports/reach/src/domain/trigger_instance_config.rs, backend/supports/reach/src/domain/trigger_scene.rs
https://github.com/kube-rs/kube/issues/1486
=> solve build failure caused by dependency api changes

Cargo.toml, backend/gateways/spacegate-plugins/src/lib.rs, backend/gateways/spacegate-plugins/src/plugin/anti_replay.rs, backend/gateways/spacegate-plugins/src/plugin/op_redis_publisher.rs, backend/services/spacegate/Cargo.toml, backend/services/spacegate/src/main.rs, backend/spi/spi-conf/src/serv.rs, backend/spi/spi-conf/src/serv/pg/conf_pg_config_serv.rs, backend/spi/spi-conf/tests/spi_conf_api_test.rs, backend/spi/spi-conf/tests/spi_conf_listener_test.rs, backend/spi/spi-conf/tests/spi_conf_nacos_compatible_test.rs, backend/spi/spi-conf/tests/spi_conf_test_common.rs
1. fix spi-conf tests
2. fix spacegate's build errors
=> spi-conf: fix spi-conf tests

.github/workflows/service-all-push.yml, .github/workflows/service-all-release.yml, .github/workflows/space-gateway-docker-push.yml, .github/workflows/space-gateway-docker-release.yml, Cargo.toml, backend/middlewares/event/src/api/ca/event_connect_api.rs, backend/middlewares/event/src/api/ci.rs, backend/middlewares/event/src/api/ci/event_message_api.rs, backend/middlewares/event/src/api/ci/event_topic_api.rs, backend/middlewares/event/src/domain/event_message.rs, backend/middlewares/event/src/domain/event_topic.rs, backend/middlewares/event/src/dto/event_dto.rs, backend/middlewares/event/src/event_config.rs, backend/middlewares/event/src/event_initializer.rs, backend/middlewares/event/src/mq_adapter.rs, backend/middlewares/event/src/serv/event_connect_serv.rs, backend/middlewares/event/src/serv/event_message_serv.rs, backend/middlewares/event/src/serv/event_topic_serv.rs, backend/middlewares/event/tests/test_event.rs, backend/middlewares/schedule/src/schedule_config.rs, backend/middlewares/schedule/src/serv/schedule_job_serv_v2.rs, backend/middlewares/schedule/src/serv/schedule_job_serv_v2/service.rs, backend/middlewares/schedule/tests/test_multi.rs, backend/services/bios-all/Cargo.toml, backend/services/bios-event/Cargo.toml, backend/services/bios-event/src/main.rs
1. add debug features for event
2. update mq version
3. add force sync for schedule
=> feat: add debug features for event; add force sync for schedule;
